<?php

function shift_cipher_menu() {
  $items['shift_cipher'] = array(
    'title' => 'Shift Cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['shift_cipher_success_page'] = array(
    'title' => 'Encryption complete!',
    'page callback' => 'shift_cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Enter a shift value. Positive integers only.'),
  );

  $form['direction'] = array(
    '#title' => 'Direction',
    '#type' => 'textfield',
    '#description' => t('Enter a direction, "left" or "right" only.'),
  );

  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter a phrase to be encrypted. Besides words, you may use only spaces and punctuation.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
  $shift_value = $form_state['values']['shift_value'];
  $direction = $form_state['values']['direction'];
  $phrase = $form_state['values']['phrase'];

  //calculate output here
  $output = 'testing';

  $_SESSION['shift_cipher'] = $output;
  $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
  $output = $_SESSION['shift_cipher'];

  return "
  <h3>Your encrypted phrase is: </h3><br>
  <p>$output</p>
  ";
}
